package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/marcodc74/pygo/internal/interp"
	"github.com/marcodc74/pygo/internal/lexer"
	"github.com/marcodc74/pygo/internal/loader"
)

type pyParam struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Default  string `json:"default"`
	Variadic bool   `json:"variadic"`
}

type pyFunc struct {
	Name   string    `json:"name"`
	Doc    string    `json:"doc"`
	Params []pyParam `json:"params"`
	Ret    string    `json:"ret"`
	OK     bool      `json:"ok"`
}

// cmdExtern prints a draft extern block for a Python module, built from the
// real signatures and type hints (review the types before using it).
func cmdExtern(args []string) int {
	fs := flag.NewFlagSet("extern", flag.ExitOnError)
	python := fs.String("python", "", "Python interpreter (default: PYGO_PYTHON or python3)")
	alias := fs.String("as", "", "binding name for the module")
	fs.Parse(args)
	if fs.NArg() < 2 || fs.Arg(0) != "python" {
		return fail2("usage: pygo extern [--python PATH] [--as NAME] python MODULE [NAME ...]")
	}
	module, names := fs.Arg(1), fs.Args()[2:]
	in := interp.New(&loader.Program{}, interp.Options{Python: *python, Allow: map[string]bool{"python": true}})
	raw, err := in.DescribePython(module, names)
	if err != nil {
		fmt.Fprintln(os.Stderr, "pygo extern:", err)
		return 1
	}
	var funcs []pyFunc
	if err := json.Unmarshal(raw, &funcs); err != nil {
		return fail2("unexpected answer from Python: %v", err)
	}
	fmt.Print(renderExtern(module, *alias, funcs))
	return 0
}

func renderExtern(module, alias string, funcs []pyFunc) string {
	var b strings.Builder
	b.WriteString("/// Generated by `pygo extern python " + module + "`: review the types (Any = not annotated in Python).\n")
	b.WriteString("extern python " + fmt.Sprintf("%q", module))
	if alias != "" {
		b.WriteString(" as " + alias)
	}
	b.WriteString(" {\n")
	for _, f := range funcs {
		if skip := externSkipReason(f); skip != "" {
			fmt.Fprintf(&b, "    // skipped %s: %s\n", f.Name, skip)
			continue
		}
		if f.Doc != "" {
			b.WriteString("    /// " + f.Doc + "\n")
		}
		var ps []string
		for _, p := range f.Params {
			s := p.Name + ": "
			if p.Variadic {
				s += "..."
			}
			s += p.Type
			if p.Default != "" && !p.Variadic {
				s += " = " + p.Default
			}
			ps = append(ps, s)
		}
		fmt.Fprintf(&b, "    fn %s(%s) -> !%s\n", f.Name, strings.Join(ps, ", "), f.Ret)
	}
	b.WriteString("}\n")
	return b.String()
}

func externSkipReason(f pyFunc) string {
	if !f.OK {
		return "Python does not expose its signature; declare it by hand"
	}
	if lexer.Keywords[f.Name] {
		return "its name is a Pygo keyword"
	}
	for _, p := range f.Params {
		if lexer.Keywords[p.Name] {
			return fmt.Sprintf("parameter '%s' is a Pygo keyword", p.Name)
		}
	}
	return ""
}
